#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Ensure uv is installed
pip install --upgrade uv

# Install dependencies with uv from pyproject.toml (including dev dependencies)
uv sync --all-extras

# Activate non-free and contrib components in APT sources
FILES="/etc/apt/sources.list.d/*.sources /etc/apt/sources.sources"

# Desired components
NEW_LINE="Components: main contrib non-free"

for f in $FILES; do
    [ -f "$f" ] || continue

    # Replace any Components: line with the new one
    sudo sed -i -E "s/^Components:.*/$NEW_LINE/" "$f"
done

sudo apt-get update

sudo apt-get install -y file unrar aria2 p7zip-full p7zip-rar unzip jq

uv run pre-commit install

# code --uninstall-extension ms-python.autopep8
