#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Ensure uv is installed
if ! command -v uv >/dev/null 2>&1; then
    echo "Installing uv..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
fi

# Install dependencies with uv into system interpreter
uv pip install --system --requirement requirements.txt

uv pip install --system --requirement requirements-dev.txt

#python3 -m pip install --requirement .github/workflows/constraints.txt

# Activate non-free and contrib components in APT sources
FILES="/etc/apt/sources.list.d/*.sources /etc/apt/sources.sources"

# Desired components
NEW_LINE="Components: main contrib non-free"

for f in $FILES; do
    [ -f "$f" ] || continue

    # Replace any Components: line with the new one
    sudo sed -i -E "s/^Components:.*/$NEW_LINE/" "$f"
done

sudo apt-get update

sudo apt-get install -y file unrar aria2 p7zip-full unzip jq

pre-commit install

code --uninstall-extension ms-python.autopep8
